import React from 'react'
import Head from "next/head"
import style from "../styles/layout.module.css"
import Menu from "../components/menu"
import ShoppingCart from "./shoppingCart"

const layout = ( {children, title} ) => {
  return (
    <div>

        <Head>
        <title>Github Merch {title? `| ${title}` : ""}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
       </Head>

       <Menu></Menu>

       <div className={style.container}>
        {children}
       </div>

       <ShoppingCart></ShoppingCart>

    </div>
  )
}

export default layout